from bot_studio import *
from getchat import getchat
linkedin=bot_studio.linkedin()
# linkedin.login(username='rajsaini10052000@gmail.com', password='raj2000')
false=False;true=True
cookie_list='list of cookies'
## Jp cookies

# linkedin.login_cookie(cookies=[
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1686465835,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "_ga",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "GA1.2.1016956668.1620873255",
#     "id": 1
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1693642731,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "_gcl_au",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "1.1.1427512738.1682392463",
#     "id": 2
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1689477734.131313,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "_guid",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "c18000be-c5f0-4a99-8fcf-423c819932ee",
#     "id": 3
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1688617710,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "aam_uuid",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "53296907051561973541260414925639507941",
#     "id": 4
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1701577711,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "-637568504%7CMCIDTS%7C19515%7CMCMID%7C52765148376714260811275305458812660782%7CMCAAMLH-1686630511%7C12%7CMCAAMB-1686630511%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1686032911s%7CNONE%7CMCCIDH%7C-705671678%7CvVersion%7C5.1.1",
#     "id": 5
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "1",
#     "id": 6
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1688458569.864178,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "AnalyticsSyncHistory",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQL6BA5NDeyO5QAAAYiGqIAVUCuqDP_ON7r2eULjwJEm2taq1vA3uQNyMEXzRvYe3SLnyt2QpK1XukhH0SRxhg",
#     "id": 7
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1717561709.422951,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "bcookie",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "\"v=2&90a033ca-7ba9-4699-8608-3eebea33f54e\"",
#     "id": 8
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1698044000,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "gpv_pn",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "www.linkedin.com%2Faccessibility",
#     "id": 9
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "lang",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": true,
#     "storeId": "0",
#     "value": "v=2&lang=en-us",
#     "id": 10
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1693801708.422881,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "li_sugr",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "b3e254c0-2a07-4f0f-a852-3c22ea5dce37",
#     "id": 11
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1693801702.870299,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "liap",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "true",
#     "id": 12
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1686112103.785737,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "lidc",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "\"b=VB33:s=V:r=V:a=V:p=V:g=4970:u=1201:x=1:i=1686045511:t=1686131903:v=2:sig=AQEoWOANQYEX_XBklQeXMk5ofBEnC8HC\"",
#     "id": 13
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1688458570.659575,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "lms_ads",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQEUnXlsZ4LRiAAAAYiGqIOEdnLTfs4Wq2fM94YCeEqmmQaMRGquygobFjHCTtfJ8yNfaZB3aCvBKwxcsRIAohe970G6Uzzm",
#     "id": 14
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1688458570.659648,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "lms_analytics",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQEUnXlsZ4LRiAAAAYiGqIOEdnLTfs4Wq2fM94YCeEqmmQaMRGquygobFjHCTtfJ8yNfaZB3aCvBKwxcsRIAohe970G6Uzzm",
#     "id": 15
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_cc",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "true",
#     "id": 16
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1698044000,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_ips",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "657",
#     "id": 17
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_plt",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "0.95",
#     "id": 18
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_pltp",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "www.linkedin.com%2Faccessibility",
#     "id": 19
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_ppv",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "www.linkedin.com%2Faccessibility%2C35%2C35%2C657%2C1%2C2",
#     "id": 20
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1698044000,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_tp",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "1852",
#     "id": 21
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1698044000,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "s_tslv",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "1682492000951",
#     "id": 22
# },
# {
#     "domain": ".linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "sdsc",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": true,
#     "storeId": "0",
#     "value": "1%3A1SZM1shxDNbLt36wZwCgPgvN58iw%3D",
#     "id": 23
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1688617707,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "UserMatchHistory",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQIyVsRBXQHtXgAAAYiQJMDGzcmgeGq8CMBWQDq0P2KpOHiG4XWCxzBAzfia08hyze8cU0OeiiiTppQGEfJgMq3S6zDDjFvkZ1miHtreclyySBMhQag2ZjuH-lyHuPAJTdvpnl-ASwWfwiwd6Gq8MS-skwdGJfhpP13hLMS2BmBc9BDO0blxB6S1yRy7J-I8NIQOYFxtN1r8RW63TOeJoqybZzZ1syPL9_V7IiDt7NNvIBpLG4F4h61I-0pnK4Z9PPnQdkG2cniueBYBTpCu9vST8C7QtGmTxGrb1NVpYItHzK9nvEhtIljkaZ7lxdirFnpnHGSqpG8c6wC16KbBkbZA7c4KmOQ",
#     "id": 24
# },
# {
#     "domain": ".linkedin.com",
#     "expirationDate": 1720585689.678856,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "visit",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "v=1&M",
#     "id": 25
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1717561702.870381,
#     "hostOnly": false,
#     "httpOnly": true,
#     "name": "bscookie",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "\"v=1&20210513121603699e861c-4a5e-4d71-8d38-0697f6401564AQHUTJvDkp3vq_L_s8leA8VRdbYYcOHj\"",
#     "id": 26
# },
# {
#     "domain": ".www.linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "G_AUTHUSER_H",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": true,
#     "session": true,
#     "storeId": "0",
#     "value": "0",
#     "id": 27
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1720585692.182038,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "G_ENABLED_IDPS",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "google",
#     "id": 28
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1693801702.870336,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "JSESSIONID",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "\"ajax:6172897223374103530\"",
#     "id": 29
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1717561702.870321,
#     "hostOnly": false,
#     "httpOnly": true,
#     "name": "li_at",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQEDASGXpkkBlMXIAAABiJAkr4cAAAGItDEzh1YAbXuhl3CbrqCEeX2EMWkz3d56aRZFBX3ulQVBDksoOFE5VqBXWaulfGpKI4n5SGgqZX-IHOd_2VLBBdE8_BF_dC2wcH_gssTGUOu6xSLfqDutP7yD",
#     "id": 30
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1717561702.870201,
#     "hostOnly": false,
#     "httpOnly": true,
#     "name": "li_rm",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQFnzI09v60UhQAAAYiKEtEOHkb1JfFkuKPrznuaUFK1meya6TH_NzXjp3wZmeTPw8x0LtskrgPgSGTT0u7SYNSrEV7rb9McuTu1LzAtQjBCMDmHRt0sb9YD1MBUKr8W6-BRdJnuYyq8CSv5yWPW8r8xHiZWqPznIVgO4AFpE4l3JckCi2Gl3xLiyJcik59t1dQHSVhZDCtbIVwXII-9Op4wgRDXWdDRbQcshERi1RQNI-HORAV1Tlym95yvrY2-91NjlEfnDOuw8wqBTcNgecSzK811akr5GOz-T8JOeWNVm9Ux4dysNVBBsFEb9NTnXjJWNfFDzW6dVqFUJtA",
#     "id": 31
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1701577705,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "li_theme",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "light",
#     "id": 32
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1701577705,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "li_theme_set",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "app",
#     "id": 33
# },
# {
#     "domain": ".www.linkedin.com",
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "spectroscopyId",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": true,
#     "session": true,
#     "storeId": "0",
#     "value": "50819d7d-673c-46e7-9d5c-e6fd51bbba42",
#     "id": 34
# },
# {
#     "domain": ".www.linkedin.com",
#     "expirationDate": 1687235304,
#     "hostOnly": false,
#     "httpOnly": false,
#     "name": "timezone",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "Asia/Calcutta",
#     "id": 35
# },
# {
#     "domain": "www.linkedin.com",
#     "expirationDate": 1686025750.596409,
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "ccookie",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "0001AQGJOeZlpqCkZgAAAYiQJH84IMmtTSzwQw4Pt8qC5gEiR0Bjog+YWkIobdlqt08jby7ISszimUy3YbJxDdesoEYNA15SzllD7s0Q9lYD/z5bFiNswbtxOCY6HBJP5HIuWJz2CT/+m2h1oi9YC06exBKf/H765uIqKA/gRUNDT9/5yMcmaQ==",
#     "id": 36
# },
# {
#     "domain": "www.linkedin.com",
#     "expirationDate": 1686630502.390956,
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "fcookie",
#     "path": "/",
#     "sameSite": "no_restriction",
#     "secure": true,
#     "session": false,
#     "storeId": "0",
#     "value": "AQFPPKLh5_YvHQAAAYiQJK3ToYkKqGHYZqOvUAHkTycTm5-9gg0HnP2LoyennD-2f5o48ul_COxhArZoAFHmkRhXHubKZR25czks4IDd3jyVbHjO90ZC_9Pa3O78LMy0RZArTU2N5xeRBMKctgzZxoCVJOrJrLXIAaL-A4mH5GWqiXBOwb9HXECMCdZwuGyvANHsARavUk7Kzf2a7D3uY9rUCR6hW6wR5Cj_E0BfEyMcHCdKd3zGp2YbcDfV4_4vyAbpNQMv6a4jKNny2Gvsd3B2aBvwiB6SYVvgQpiw4OwAnE0NnWrXtwHX5/jr9ncz/v5Zcjn2RJ7Aa7/mR+faQB/HuEvg==",
#     "id": 37
# },
# {
#     "domain": "www.linkedin.com",
#     "expirationDate": 1686630491.069062,
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "fid",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "AQF1-_EfEJfZBgAAAYiQJIGYQublhMfSHe2lOlKcrb16w1NCzbDZHdMWTlVNkQukTRBuY0L-fTcQ5w",
#     "id": 38
# },
# {
#     "domain": "www.linkedin.com",
#     "expirationDate": 1701475879,
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "g_state",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "{\"i_l\":0}",
#     "id": 39
# },
# {
#     "domain": "www.linkedin.com",
#     "expirationDate": 1686029289.678357,
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "li_g_recent_logout",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": false,
#     "storeId": "0",
#     "value": "v=1&true",
#     "id": 40
# },
# {
#     "domain": "www.linkedin.com",
#     "hostOnly": true,
#     "httpOnly": false,
#     "name": "PLAY_LANG",
#     "path": "/",
#     "sameSite": "unspecified",
#     "secure": false,
#     "session": true,
#     "storeId": "0",
#     "value": "en",
#     "id": 41
# },
# {
#     "domain": "www.linkedin.com",
#     "hostOnly": true,
#     "httpOnly": true,
#     "name": "PLAY_SESSION",
#     "path": "/",
#     "sameSite": "lax",
#     "secure": true,
#     "session": true,
#     "storeId": "0",
#     "value": "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InNlc3Npb25faWQiOiJiOTg5ZjZjNS1iYjUyLTQ1OTYtOTQyYS0wNjIwOTNlZTg3NDh8MTY4NTg4NjUyNyIsImFsbG93bGlzdCI6Int9IiwicmVjZW50bHktc2VhcmNoZWQiOiIiLCJyZWZlcnJhbC11cmwiOiJodHRwczovL3d3dy5nb29nbGUuY29tLyIsImFpZCI6IiIsInJlY2VudGx5LXZpZXdlZCI6IjU1MTM2MHwxMzM5MzY0IiwiQ1BULWlkIjoiwoXDtcOYwpHDikVLJcKZwqXDqWbCgUDDn8OTIiwiZXhwZXJpZW5jZSI6ImVudGl0eSIsInRyayI6IiJ9LCJuYmYiOjE2ODU4ODY1MjcsImlhdCI6MTY4NTg4NjUyN30.H8xnjjMnWDdfHn1ST8PiHaFMQ-SBKvkTl2bN6I_Hwt0",
#     "id": 42
# }
# ])

## Rajcookies

linkedin.login_cookie(cookies=[
{
    "domain": ".linkedin.com",
    "expirationDate": 1695076374,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_gcl_au",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1.1.1427512738.1682392463",
    "id": 1
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1702005969.415399,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_guid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1811db51-594b-4fb8-85b3-399ce6c3b752",
    "id": 2
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1696822064,
    "hostOnly": false,
    "httpOnly": false,
    "name": "aam_uuid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "53296907051561973541260414925639507941",
    "id": 3
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1709782028,
    "hostOnly": false,
    "httpOnly": false,
    "name": "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "-637568504%7CMCIDTS%7C19610%7CMCMID%7C52765148376714260811275305458812660782%7CMCAAMLH-1694834828%7C12%7CMCAAMB-1694834828%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1694237228s%7CNONE%7CMCCIDH%7C531661599%7CvVersion%7C5.1.1",
    "id": 4
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "1",
    "id": 5
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1696821969.107622,
    "hostOnly": false,
    "httpOnly": false,
    "name": "AnalyticsSyncHistory",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQJ3-AcU-VdirQAAAYp5J9iigLf2_6mm_s7DhdCZKbcnLzZxtmoNDGamdK_00TBJnJ_a9WT_lrW9JOWEVoZ24w",
    "id": 6
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1725766027.927338,
    "hostOnly": false,
    "httpOnly": false,
    "name": "bcookie",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "\"v=2&90a033ca-7ba9-4699-8608-3eebea33f54e\"",
    "id": 7
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1698044000,
    "hostOnly": false,
    "httpOnly": false,
    "name": "gpv_pn",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "www.linkedin.com%2Faccessibility",
    "id": 8
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "lang",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "v=2&lang=en-us",
    "id": 9
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1702006026.92725,
    "hostOnly": false,
    "httpOnly": false,
    "name": "li_sugr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "b3e254c0-2a07-4f0f-a852-3c22ea5dce37",
    "id": 10
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1702006020.820551,
    "hostOnly": false,
    "httpOnly": false,
    "name": "liap",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "true",
    "id": 11
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1694230537.826566,
    "hostOnly": false,
    "httpOnly": false,
    "name": "lidc",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "\"b=VP00:s=V:r=V:a=V:p=V:g=365:u=3:x=1:i=1694249859:t=1694250337:v=2:sig=AQEdHn81QQZ68UM4iNx6sLDW9x3U5Kgb\"",
    "id": 12
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1696821969.979045,
    "hostOnly": false,
    "httpOnly": false,
    "name": "lms_ads",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQFDuGMkkn8ZZwAAAYp5J90aBUnjgrqs6_ShOw8u-0rR1VMGDK6kGf-7ulrbRkGoI_LtBZm33-fnIfHM6kZgxw6wPh7wjJoy",
    "id": 13
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1696821969.979154,
    "hostOnly": false,
    "httpOnly": false,
    "name": "lms_analytics",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQFDuGMkkn8ZZwAAAYp5J90aBUnjgrqs6_ShOw8u-0rR1VMGDK6kGf-7ulrbRkGoI_LtBZm33-fnIfHM6kZgxw6wPh7wjJoy",
    "id": 14
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_cc",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "true",
    "id": 15
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1698044000,
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_ips",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "657",
    "id": 16
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_plt",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "0.95",
    "id": 17
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_pltp",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "www.linkedin.com%2Faccessibility",
    "id": 18
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_ppv",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "www.linkedin.com%2Faccessibility%2C35%2C35%2C657%2C1%2C2",
    "id": 19
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1698044000,
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_tp",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1852",
    "id": 20
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1698044000,
    "hostOnly": false,
    "httpOnly": false,
    "name": "s_tslv",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1682492000951",
    "id": 21
},
{
    "domain": ".linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "sdsc",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "1%3A1SZM1shxDNbLt36wZwCgPgvN58iw%3D",
    "id": 22
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1696822024,
    "hostOnly": false,
    "httpOnly": false,
    "name": "UserMatchHistory",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQJniFzZbPpP7gAAAYp5KLFN6igNQTZSssMaExyodeMfTcs9u-7SVhDA8zsO9feCAxG2oINZG6YjOOuFb7CkueMlZXN7OzTOSuwMwqqfeBZ6qgxdyAeqg_SJbiP6RV3G2fKp1sfuVo_gIqC4RGTbLxffvYRF9Cjo8B75qifqX5_d1Llarps7e393gEXGnT54iJItrvFC7C2W3bCfGDQWd4Ps8usKsjMrYWsjpFvaf9qhk3VaRyFum-xEsUmQn2SmdYUl4eYkTVCmmlbrbAmuPapXAD568QQ8CqRYVb55Rehyqvbr9Y7qjAgXxzz69aP7s0qZAyrBfc4on0empmSB6QV3KQEPs-E",
    "id": 23
},
{
    "domain": ".linkedin.com",
    "expirationDate": 1728790014.832166,
    "hostOnly": false,
    "httpOnly": false,
    "name": "visit",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "v=1&M",
    "id": 24
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1725766021.820704,
    "hostOnly": false,
    "httpOnly": true,
    "name": "bscookie",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "\"v=1&20210513121603699e861c-4a5e-4d71-8d38-0697f6401564AQHUTJvDkp3vq_L_s8leA8VRdbYYcOHj\"",
    "id": 25
},
{
    "domain": ".www.linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "G_AUTHUSER_H",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "0",
    "id": 26
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1721707654.945246,
    "hostOnly": false,
    "httpOnly": false,
    "name": "G_ENABLED_IDPS",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "google",
    "id": 27
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1702006020.820581,
    "hostOnly": false,
    "httpOnly": false,
    "name": "JSESSIONID",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "\"ajax:7624154989207462670\"",
    "id": 28
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1725766020.820428,
    "hostOnly": false,
    "httpOnly": true,
    "name": "li_at",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQEDAUP4xZcC3_rzAAABinkopBUAAAGKnTUoFU0ActbyVWN3WJ14qfjhEY2RgfTZT5KtgZk6H0CueEzOT9fprHkCe4Y-jqaLd4CH1Sqnou1iigKAKWyPX_rTQGQpYEum8akaCQ6J_36Q8upoglYXYMpS",
    "id": 29
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1725766020.820263,
    "hostOnly": false,
    "httpOnly": true,
    "name": "li_rm",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "AQFnzI09v60UhQAAAYiKEtEOHkb1JfFkuKPrznuaUFK1meya6TH_NzXjp3wZmeTPw8x0LtskrgPgSGTT0u7SYNSrEV7rb9McuTu1LzAtQjBCMDmHRt0sb9YD1MBUKr8W6-BRdJnuYyq8CSv5yWPW8r8xHiZWqPznIVgO4AFpE4l3JckCi2Gl3xLiyJcik59t1dQHSVhZDCtbIVwXII-9Op4wgRDXWdDRbQcshERi1RQNI-HORAV1Tlym95yvrY2-91NjlEfnDOuw8wqBTcNgecSzK811akr5GOz-T8JOeWNVm9Ux4dysNVBBsFEb9NTnXjJWNfFDzW6dVqFUJtA",
    "id": 30
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1709782023,
    "hostOnly": false,
    "httpOnly": false,
    "name": "li_theme",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "light",
    "id": 31
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1709782023,
    "hostOnly": false,
    "httpOnly": false,
    "name": "li_theme_set",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "app",
    "id": 32
},
{
    "domain": ".www.linkedin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "spectroscopyId",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "50819d7d-673c-46e7-9d5c-e6fd51bbba42",
    "id": 33
},
{
    "domain": ".www.linkedin.com",
    "expirationDate": 1695439623,
    "hostOnly": false,
    "httpOnly": false,
    "name": "timezone",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "Asia/Calcutta",
    "id": 34
},
{
    "domain": "www.linkedin.com",
    "expirationDate": 1702699659,
    "hostOnly": true,
    "httpOnly": false,
    "name": "g_state",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "{\"i_l\":0}",
    "id": 35
},
{
    "domain": "www.linkedin.com",
    "expirationDate": 1694233614.831849,
    "hostOnly": true,
    "httpOnly": false,
    "name": "li_g_recent_logout",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "v=1&true",
    "id": 36
},
{
    "domain": "www.linkedin.com",
    "hostOnly": true,
    "httpOnly": false,
    "name": "PLAY_LANG",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "en",
    "id": 37
},
{
    "domain": "www.linkedin.com",
    "hostOnly": true,
    "httpOnly": true,
    "name": "PLAY_SESSION",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InNlc3Npb25faWQiOiJiOTg5ZjZjNS1iYjUyLTQ1OTYtOTQyYS0wNjIwOTNlZTg3NDh8MTY4NTg4NjUyNyIsImFsbG93bGlzdCI6Int9IiwicmVjZW50bHktc2VhcmNoZWQiOiIiLCJyZWZlcnJhbC11cmwiOiJodHRwczovL3d3dy5nb29nbGUuY29tLyIsImFpZCI6IiIsInJlY2VudGx5LXZpZXdlZCI6IjU1MTM2MHwxMzM5MzY0IiwiQ1BULWlkIjoiwoXDtcOYwpHDikVLJcKZwqXDqWbCgUDDn8OTIiwiZmxvd1RyYWNraW5nSWQiOiJZYy8rWjRuMFNRRzcyVlhHbEFWTm5BPT0iLCJleHBlcmllbmNlIjoiZW50aXR5IiwidHJrIjoiIn0sIm5iZiI6MTY4NzE2NzYzNSwiaWF0IjoxNjg3MTY3NjM1fQ.BUQnCkZ4aSwyJi5ZmOeB3KUHumWH6wPnu_VF1d6x7ww",
    "id": 38
}
])

# print("getchat",getchat())
# linkData = ['https://www.linkedin.com/posts/jagdish-saini-8098b1138_python-cheat-sheet-activity-7067132128068591616-PqGC?utm_source=share&utm_medium=member_desktop',
# 'https://www.linkedin.com/posts/jagdish-saini-8098b1138_js-cheat-sheet-activity-7066245535468273664-j6HV?utm_source=share&utm_medium=member_desktop',
# 'https://www.linkedin.com/feed/update/urn:li:activity:7069752205876043777?utm_source=share&utm_medium=member_desktop',
# 'https://www.linkedin.com/feed/update/urn:li:activity:7068547966940135424?utm_source=share&utm_medium=member_desktop',
# 'https://www.linkedin.com/posts/jagdish-saini-8098b1138_css-handwritten-notes-activity-7068547341502324736-f5vd?utm_source=share&utm_medium=member_desktop']

for data in getchat():
    linkedin.open(data)
    dataComment = linkedin.get_comments()
    # print("len(dataComment['body'])===================================================",len(dataComment['body']))
    if(len(dataComment['body'])>0):
        split_data = dataComment['body'][0]['Comment'].split("\n")
        # print("get_comment=================================================",split_data[len(split_data)-3])
        linkedin.comment_on_post(post_link=data, comment=split_data[len(split_data)-3])